name: GitHub Actions Demo
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 21.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
      - name: unit tests
        run: npm run test
      - name: build storybook
        run: npm run build-storybook
      - name: linter
        run: npm run lint
